name: Update Study Notes

on:
  schedule:
    - cron: "0 13 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SHEET_CSV_URL: ${{ secrets.SHEET_CSV_URL }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Inspect pyproject header
        run: |
          python - <<'PY'
          import pathlib
          data = pathlib.Path('pyproject.toml').read_bytes()
          print(data[:32])
          PY

      - name: Install leetnotes
        run: |
          python -m pip install --upgrade pip
          python -m pip install .

      - name: Regenerate Blind 75 notes
        run: leetnotes

      - name: Regenerate NeetCode 150 notes
        env:
          SHEET_CSV_URL_NEETCODE150: ${{ secrets.SHEET_CSV_URL_NEETCODE150 }}
        run: leetnotes --profile neetcode150

      - name: Commit and push if changed
        run: |
          git add "Notes/blind75.md" "Notes/neetcode150.md" "Problems" "Problems/README.md"
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git config --global user.name "${{ secrets.COMMIT_USER_NAME }}"
            git config --global user.email "${{ secrets.COMMIT_USER_EMAIL }}"
            git commit -m "Update study notes"
            git push
          fi
