name: Update Blind 75 Notes

on:
  schedule:
    - cron: "0 13 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SHEET_CSV_URL: ${{ secrets.SHEET_CSV_URL }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Regenerate Blind 75 notes
        run: python "Scripts/blind75.py"

      - name: Commit and push if changed
        run: |
          git add "Notes/blind75.md" "Problems/README.md" "Problems"
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git config --global user.name "${{ secrets.COMMIT_USER_NAME }}"
            git config --global user.email "${{ secrets.COMMIT_USER_EMAIL }}"
            git commit -m "Update Blind 75 Notes"
            git push
          fi
