name: Update Study Notes

on:
  schedule:
    - cron: "0 13 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: src
      SHEET_CSV_URL: ${{ secrets.SHEET_CSV_URL }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Sync solutions from spreadsheet
        env:
          SOLUTIONS_CSV_URL: ${{ secrets.SOLUTIONS_CSV_URL }}
        run: python -m leetnotes.cli --solutions-only

      - name: Regenerate Blind 75 notes
        run: python -m leetnotes.cli

      - name: Regenerate NeetCode 150 notes
        env:
          SHEET_CSV_URL_NEETCODE150: ${{ secrets.SHEET_CSV_URL_NEETCODE150 }}
        run: python -m leetnotes.cli --profile neetcode150

      - name: Commit and push if changed
        run: |
          git add -f "Notes/blind75.md" "Notes/neetcode150.md" "Problems" "Problems/README.md"
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git config --global user.name "${{ secrets.COMMIT_USER_NAME }}"
            git config --global user.email "${{ secrets.COMMIT_USER_EMAIL }}"
            git commit -m "Update study notes"
            git push
          fi
